# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('rwfec_timesTwo', PACKAGE = 'rwfec', x)
}

rcpp_hello <- function() {
    .Call('rwfec_rcpp_hello', PACKAGE = 'rwfec')
}

rwconv <- function(h, x) {
    .Call('rwfec_rwconv', PACKAGE = 'rwfec', h, x)
}

rwviterbi <- function(x, G, v) {
    .Call('rwfec_rwviterbi', PACKAGE = 'rwfec', x, G, v)
}

sinc <- function(x) {
    .Call('rwfec_sinc', PACKAGE = 'rwfec', x)
}

